package com.doocker.crm.po;

public class Position {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column position.id
     *
     * @mbggenerated Thu Jul 13 15:41:52 CST 2017
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column position.dept_id
     *
     * @mbggenerated Thu Jul 13 15:41:52 CST 2017
     */
    private Integer deptId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column position.dept_name
     *
     * @mbggenerated Thu Jul 13 15:41:52 CST 2017
     */
    private String deptName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column position.position_name
     *
     * @mbggenerated Thu Jul 13 15:41:52 CST 2017
     */
    private String positionName;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column position.id
     *
     * @return the value of position.id
     *
     * @mbggenerated Thu Jul 13 15:41:52 CST 2017
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column position.id
     *
     * @param id the value for position.id
     *
     * @mbggenerated Thu Jul 13 15:41:52 CST 2017
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column position.dept_id
     *
     * @return the value of position.dept_id
     *
     * @mbggenerated Thu Jul 13 15:41:52 CST 2017
     */
    public Integer getDeptId() {
        return deptId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column position.dept_id
     *
     * @param deptId the value for position.dept_id
     *
     * @mbggenerated Thu Jul 13 15:41:52 CST 2017
     */
    public void setDeptId(Integer deptId) {
        this.deptId = deptId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column position.dept_name
     *
     * @return the value of position.dept_name
     *
     * @mbggenerated Thu Jul 13 15:41:52 CST 2017
     */
    public String getDeptName() {
        return deptName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column position.dept_name
     *
     * @param deptName the value for position.dept_name
     *
     * @mbggenerated Thu Jul 13 15:41:52 CST 2017
     */
    public void setDeptName(String deptName) {
        this.deptName = deptName == null ? null : deptName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column position.position_name
     *
     * @return the value of position.position_name
     *
     * @mbggenerated Thu Jul 13 15:41:52 CST 2017
     */
    public String getPositionName() {
        return positionName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column position.position_name
     *
     * @param positionName the value for position.position_name
     *
     * @mbggenerated Thu Jul 13 15:41:52 CST 2017
     */
    public void setPositionName(String positionName) {
        this.positionName = positionName == null ? null : positionName.trim();
    }
}