package com.doocker.crm.po;

import java.util.Date;

public class Staff {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column staff.id
     *
     * @mbggenerated Thu Jul 13 15:41:52 CST 2017
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column staff.name
     *
     * @mbggenerated Thu Jul 13 15:41:52 CST 2017
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column staff.username
     *
     * @mbggenerated Thu Jul 13 15:41:52 CST 2017
     */
    private String username;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column staff.password
     *
     * @mbggenerated Thu Jul 13 15:41:52 CST 2017
     */
    private String password;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column staff.sex
     *
     * @mbggenerated Thu Jul 13 15:41:52 CST 2017
     */
    private Integer sex;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column staff.birthday
     *
     * @mbggenerated Thu Jul 13 15:41:52 CST 2017
     */
    private Date birthday;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column staff.entry
     *
     * @mbggenerated Thu Jul 13 15:41:52 CST 2017
     */
    private Date entry;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column staff.position_id
     *
     * @mbggenerated Thu Jul 13 15:41:52 CST 2017
     */
    private Integer positionId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column staff.id
     *
     * @return the value of staff.id
     *
     * @mbggenerated Thu Jul 13 15:41:52 CST 2017
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column staff.id
     *
     * @param id the value for staff.id
     *
     * @mbggenerated Thu Jul 13 15:41:52 CST 2017
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column staff.name
     *
     * @return the value of staff.name
     *
     * @mbggenerated Thu Jul 13 15:41:52 CST 2017
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column staff.name
     *
     * @param name the value for staff.name
     *
     * @mbggenerated Thu Jul 13 15:41:52 CST 2017
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column staff.username
     *
     * @return the value of staff.username
     *
     * @mbggenerated Thu Jul 13 15:41:52 CST 2017
     */
    public String getUsername() {
        return username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column staff.username
     *
     * @param username the value for staff.username
     *
     * @mbggenerated Thu Jul 13 15:41:52 CST 2017
     */
    public void setUsername(String username) {
        this.username = username == null ? null : username.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column staff.password
     *
     * @return the value of staff.password
     *
     * @mbggenerated Thu Jul 13 15:41:52 CST 2017
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column staff.password
     *
     * @param password the value for staff.password
     *
     * @mbggenerated Thu Jul 13 15:41:52 CST 2017
     */
    public void setPassword(String password) {
        this.password = password == null ? null : password.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column staff.sex
     *
     * @return the value of staff.sex
     *
     * @mbggenerated Thu Jul 13 15:41:52 CST 2017
     */
    public Integer getSex() {
        return sex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column staff.sex
     *
     * @param sex the value for staff.sex
     *
     * @mbggenerated Thu Jul 13 15:41:52 CST 2017
     */
    public void setSex(Integer sex) {
        this.sex = sex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column staff.birthday
     *
     * @return the value of staff.birthday
     *
     * @mbggenerated Thu Jul 13 15:41:52 CST 2017
     */
    public Date getBirthday() {
        return birthday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column staff.birthday
     *
     * @param birthday the value for staff.birthday
     *
     * @mbggenerated Thu Jul 13 15:41:52 CST 2017
     */
    public void setBirthday(Date birthday) {
        this.birthday = birthday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column staff.entry
     *
     * @return the value of staff.entry
     *
     * @mbggenerated Thu Jul 13 15:41:52 CST 2017
     */
    public Date getEntry() {
        return entry;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column staff.entry
     *
     * @param entry the value for staff.entry
     *
     * @mbggenerated Thu Jul 13 15:41:52 CST 2017
     */
    public void setEntry(Date entry) {
        this.entry = entry;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column staff.position_id
     *
     * @return the value of staff.position_id
     *
     * @mbggenerated Thu Jul 13 15:41:52 CST 2017
     */
    public Integer getPositionId() {
        return positionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column staff.position_id
     *
     * @param positionId the value for staff.position_id
     *
     * @mbggenerated Thu Jul 13 15:41:52 CST 2017
     */
    public void setPositionId(Integer positionId) {
        this.positionId = positionId;
    }
}